title: Letcloudinit
logo: null
author: Vinoth
description: aws,gcp,azure,Automation,AIops,Devops
email: info@letcloudinit.com
address: Chennai,India
copyright: Copyright &copy; 2020 Letcloudinit
menu:
  - name: About
    link: /about
  - name: Blog
    link: /blog
  - name: Contact
    link: /contact
google-analytics: UA-184809044-1
disqus-identifier: null
hero:
  hero-title: Hi! All <br> Welcome to <br> Cloud World
social:
  - icon: ti-facebook
    link: '#'
  - icon: ti-instagram
    link: '#'
  - icon: ti-dribbble
    link: '#'
  - icon: ti-twitter
    link: '#'
blurb: >-
  Hi All, Welcome to Letcloudinit. I created this webpage to share the new
  technology and my experience in cloud with you friends.
  Hope you enjoy the blog reading. I am not a expert in english,your feedback more helpful if you find something wrong in article. 
blurb-btn-link: /blog
blurb-btn-name: know more
work-process:
  - title: Research and Plan
    icon: assets/images/icons/plan.png
    content: >-
      Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
      tempor incididunt ut labore et dolore magna aliqua.
  - title: Design and Develop
    icon: assets/images/icons/design.png
    content: >-
      Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
      tempor incididunt ut labore et dolore magna aliqua.
  - title: Deliver
    icon: assets/images/icons/print.png
    content: >-
      Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
      tempor incididunt ut labore et dolore magna aliqua.
team:
  - title: Jack Schenziwe
    image: assets/images/team/member-1.png
    designation: Project Manager
  - title: Julias Carlie
    image: assets/images/team/member-2.png
    designation: Web Developer
  - title: John Doe
    image: assets/images/team/member-3.png
    designation: Designer
skills-title: Skills
skills:
  - name: Web Design
    color: '#fdb157'
    value: 90%
  - name: Logo Design
    color: '#9473e6'
    value: 60%
  - name: After Effects
    color: '#bdecf6'
    value: 80%
  - name: Web App
    color: '#ffbcaa'
    value: 70%
experience-title: Experience
experience:
  - name: Junior UX Designer
    icon: icon-1.png
    date: Jan 2007 - Feb 2009
    organization: WEBEX
  - name: UX & UI Designer
    icon: icon-2.png
    date: Mar 2009 - Aug 2014
    organization: AUGMEDIX
  - name: Senior UI Designer
    icon: icon-3.png
    date: Sep 2014 - Present
    organization: THEMEFISHER
education-title: Education
education:
  - name: Marters in UX Design
    date: 2006
    organization: Masassusets Institute of Technology
  - name: Honours in Fine Arts
    date: 2004
    organization: Harvard University
  - name: Higher Secondary Certificat
    date: 2000
    organization: Cardiff School
  - name: Secondary School Certificate
    date: 1998
    organization: Cardiff School
services-title: Services
services:
  - name: UI Design
    icon: ti-palette
    description: >-
      Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
      tempor incididunt ut labore et dolore magna aliqua.
    active: null
  - name: UX Design
    icon: ti-vector
    description: >-
      Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
      tempor incididunt ut labore et dolore magna aliqua.
    active: true
  - name: Interaction Design
    icon: ti-panel
    description: >-
      Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
      tempor incididunt ut labore et dolore magna aliqua.
    active: null
portfolio-home-items:
  - image: assets/images/portfolio/item-1.png
    url: '#'
  - image: assets/images/portfolio/item-2.png
    url: '#'
  - image: assets/images/portfolio/item-3.png
    url: '#'
  - image: assets/images/portfolio/item-4.png
    url: '#'
  - image: assets/images/portfolio/item-5.png
    url: '#'
portfolio-label:
  - title: UI/UX Design
    type: design
  - title: BRANDING
    type: branding
  - title: ILLUSTRATION
    type: illustration
portfolio-items:
  - image: assets/images/portfolio/item-1.png
    url: '#'
    portfolio-type:
      - type: design
      - type: illustration
  - image: assets/images/portfolio/item-2.png
    url: '#'
    portfolio-type:
      - type: branding
  - image: assets/images/portfolio/item-3.png
    url: '#'
    portfolio-type:
      - type: illustration
  - image: assets/images/portfolio/item-6.png
    url: '#'
    portfolio-type:
      - type: design
      - type: branding
  - image: assets/images/portfolio/item-8.png
    url: '#'
    portfolio-type:
      - type: illustration
  - image: assets/images/portfolio/item-5.png
    url: '#'
    portfolio-type:
      - type: design
  - image: assets/images/portfolio/item-1.png
    url: '#'
    portfolio-type:
      - type: branding
  - image: assets/images/portfolio/item-3.png
    url: '#'
    portfolio-type:
      - type: design
      - type: illustration
      - type: branding
  - image: assets/images/portfolio/item-7.png
    url: '#'
    portfolio-type:
      - type: illustration
testimonial-items:
  - name: Jesica Gomez
    image: assets/images/testimonial/client-1.png
    designation: 'CEO, Funder'
    content: >-
      Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
      tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim
      veniam, <strong>quis nostrud exercitation ullamco laboris nisi ut aliquip
      ex ea commodo consequat.</strong> Duis aute irure dolor in reprehenderit
      in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
  - name: Jesica Gomez
    image: assets/images/testimonial/client-1.png
    designation: 'CEO, Funder'
    content: >-
      Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
      tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim
      veniam, <strong>quis nostrud exercitation ullamco laboris nisi ut aliquip
      ex ea commodo consequat.</strong> Duis aute irure dolor in reprehenderit
      in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
  - name: Jesica Gomez
    image: assets/images/testimonial/client-1.png
    designation: 'CEO, Funder'
    content: >-
      Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
      tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim
      veniam, <strong>quis nostrud exercitation ullamco laboris nisi ut aliquip
      ex ea commodo consequat.</strong> Duis aute irure dolor in reprehenderit
      in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
client-slider-items:
  - logo: assets/images/clients-logo/client-logo-1.png
    url: '#'
  - logo: assets/images/clients-logo/client-logo-2.png
    url: '#'
  - logo: assets/images/clients-logo/client-logo-3.png
    url: '#'
  - logo: assets/images/clients-logo/client-logo-4.png
    url: '#'
  - logo: assets/images/clients-logo/client-logo-5.png
    url: '#'
  - logo: assets/images/clients-logo/client-logo-1.png
    url: '#'
  - logo: assets/images/clients-logo/client-logo-2.png
    url: '#'
  - logo: assets/images/clients-logo/client-logo-3.png
    url: '#'
  - logo: assets/images/clients-logo/client-logo-4.png
    url: '#'
  - logo: assets/images/clients-logo/client-logo-5.png
    url: '#'
contact-title: Contact Info
contact-email: info@letcloudinit.com
